export const SESSIONS_TOKENS_SERVICE = Symbol('SESSIONS_TOKENS_SERVICE');
export const SESSIONS_SERVICE_PROVIDER = Symbol('SESSIONS_SERVICE');
export const AUTH_SERVICE_PROVIDER = Symbol('AUTH_SERVICE_PROVIDER');
export const USERS_SERVICE_PROVIDER = Symbol('USERS_SERVICE_PROVIDER');
